apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/your-org/your-repo.git
      type: git
      secret: github-repo-creds
